# Executor configuration
executor: slurm

# Default resources: These are the baseline resources allocated to each rule if not overridden by set-resources.
default-resources:
  - mem_mb=1000         # Memory in megabytes allocated to each task
  - runtime=60          # Runtime in minutes for each task
  - constraint=''       # SLURM constraints (e.g., specific nodes), empty by default
  - partition=short     ## MODIFIED

# Throttling to prevent overloading the scheduler
max-jobs-per-second: 100           # Maximum number of jobs submitted per second
max-status-checks-per-second: 100  # Maximum number of job status checks per second

# Core and job handling
local-cores: 1          # Number of cores to use for local rules
latency-wait: 60        # Time in seconds to wait for filesystems to catch up (important for NFS)
jobs: 200               # Maximum number of concurrent jobs

# Fault tolerance
keep-going: True        # Continue with independent jobs even if some jobs fail
rerun-incomplete: True  # Rerun jobs that were started but didn't complete

# Software deployment settings
software-deployment-method: 
  - conda               # Use Conda for handling software dependencies
  - apptainer           # Use Apptainer for handling software dependencies
conda-frontend: "conda" # Specify the frontend for Conda (alternative could be mamba)
apptainer-args: "-B /fast,/fast"     # Additional arguments to pass to Apptainer


## MODIFIED
set-resources:
  - install_T2T_BSgenome_tarball:partition=medium
  - samtools_faindex:partition=medium
  - create_haplotag_table:partition=medium
  - mosaiClassifier_calc_probs:partition=medium
  - create_haplotag_likelihoods:partition=medium
  - mosaiClassifier_make_call:partition=medium
  - mosaiClassifier_make_call_biallelic:partition=medium
  - call_complex_regions:partition=medium
  - mergeSortBams:partition=medium
  - regenotype_SNVs:partition=medium
  - call_SNVs_bcftools_chrom:partition=medium
  - run_strandphaser_per_chrom:partition=medium
